### PR TITLE
Fix PyPI deployment

### PR DESCRIPTION
**Pull request by rw1nkler**
This PR fixes PyPI package deployment

### CODE REVIEW

**Comment by rw1nkler** [comment]
This PR fails on RTD check, which is fixed by #16 (Due to that #16 should be merged first)

**Comment by mithro** [comment]
Need to rebase this.

**Comment by rw1nkler** [comment]
Actually, it seems that the #18 introduced a similar change. 

However, in this PR I left empty `before_install` step in Travis CI. 
It should save a few minutes. Currently, we are creating the environment and then removing it.

**Review by mithro — APPROVED** [review]
LGTM!

**Pull request merged**
